### PR TITLE
Updates for PowerModels v0.13

### PR DESCRIPTION
**Pull request by ccoffrin**
@nicoleepp I am not sure how to update the frontend to support optional branch values.  Other updates should be done.  Can you provide a PR into this branch that resolves the frontend issue?

### CODE REVIEW

**Comment by ccoffrin** [comment]
@eperim, @nicoleepp any proposals on this update?

**Comment by eperim** [comment]
@ccoffrin sorry for the delay, I was away last week. I just started looking into this, but things fail right away for me because `PowerModels.parse_file` seems to have a slightly different behaviour now. The dictionary it is parsing in the newer version doesn't have line rating information anymore (at least for case 14). Is that intended?

PowerModels 0.12.5:
```julia
julia> pmc = PowerModels.parse_file(case_files["case14"])

julia> keys(pmc["branch"]["1"])
Base.KeySet for a Dict{String,Any} with 17 entries. Keys:
  "br_r"
  "rate_a"
  "shift"
  "br_x"
  "g_to"
  "g_fr"
  "source_id"
  "b_fr"
  "f_bus"
  "br_status"
  "t_bus"
  "b_to"
  "index"
  "angmin"
  "angmax"
  "transformer"
  "tap"
```

PowerModels 0.13.0:
```julia 
julia> pmc = PowerModels.parse_file(case_files["case14"])

julia> keys(pmc["branch"]["1"])
Base.KeySet for a Dict{String,Any} with 16 entries. Keys:
  "br_r"
  "shift"
  "br_x"
  "g_to"
  "g_fr"
  "source_id"
  "b_fr"
  "f_bus"
  "br_status"
  "t_bus"
  "b_to"
  "index"
  "angmin"
  "angmax"
  "transformer"
  "tap"
```

**Comment by ccoffrin** [comment]
@eperim, that is correct.  One of the breaking changes in PowerModels v0.13 was to make `rate_a` an optional parameter.  If it is omitted that means the line has limit in the optimization problem.

The simple fix to replicate the old semantics is to call `PowerModels.calc_thermal_limits!(data)`, which adds a reasonable `rate_a` value to all of the branches.

**Comment by eperim** [comment]
@ccoffrin, nice, that seems to be all we need to solve to make it work. Would you rather have the call to `PowerModels.calc_thermal_limits!` be the default or not when creating a `Network` from a matpower case?

Any other thing you'd like the frontend extended to? All tests work fine for me now (will open a PR to your branch).

**Comment by ccoffrin** [comment]
@eperim PowerModels now supports omitting line flow limits (it can make a big impact on runtime performance), so we will not apply `PowerModels.calc_thermal_limits!` when loading the data from a file.   However, when creating the front end's `Network` structure, I'll leave it up to you if you would like to support these optional line flow limits or not.  I have a slight preference for the front end to also clearly indicate when line flow limits are not specified in the data, but I don't want to impose a major development effort unless there is appetite for it.

**Comment by eperim** [comment]
Oh, no problem, I'll leave the default as not running `PowerModels.calc_thermal_limits!` (so it will be clear when the data does not have this information), but add a keyword to the constructor such that it is easy to have that added.

This https://github.com/lanl-ansi/PowerModelsAnnex.jl/pull/63 should make the tests pass, without changing your intended behaviour.

**Pull request merged**
