### PR TITLE
REF: remove Julia < v1.0 compatibility

### PR DESCRIPTION
**Pull request by ccoffrin**
@pseudocubic, given the updates I made in https://github.com/lanl-ansi/PowerModelsAnnex.jl/pull/46, I think we can delete this branch.  Do you see any features that I missed?

### CODE REVIEW

**Comment by pseudocubic** [comment]
It looks like the tests weren't updated to use `import`, which I have been doing to keep everything consistent, but this may be a matter of preference. I also had updated the `model` files, but based on our discussion yesterday, `using` in that context makes more sense.

Otherwise it looks like #46 got all the important things.

**Comment by ccoffrin** [comment]
I am open to updating the tests to use `import` instead of `using`; but it might lead to an issue with running tests on the example "models" as you suggest.  Would you like to explore that avenue?  If not, we can proceed with `master` as is.

**Comment by pseudocubic** [comment]
sure, I'll take a look at it today, and update you here

**Comment by pseudocubic** [comment]
@ccoffrin Looks like updating the tests works fine, this should be ready to merge

**Pull request merged**
