### PR TITLE
Fix frontend convergence and add convergence tests

### PR DESCRIPTION
**Pull request by nicoleepp**
Fixes this error:

```julia
exception =
│    KeyError: key "status" not found
│    Stacktrace:
│     [1] getindex at ./dict.jl:478 [inlined]
│     [2] converged(::Network) at /Users/nicoleepp/.julia/packages/PowerModelsAnnex/gTyan/src/frontend/frontend.jl:1141
```

### CODE REVIEW

**Comment by eperim** [comment]
LGTM

**Comment by ccoffrin** [comment]
`ALMOST_LOCALLY_SOLVED` and `USER_LIMIT` are also valid status values in JuMP v0.19, but `OPTIMAL` and `LOCALLY_SOLVED` should be expected in normal conditions.

**Comment by nicoleepp** [comment]
I can add those two status values

> `ALMOST_LOCALLY_SOLVED` and `USER_LIMIT` are also valid status values in JuMP v0.19, but `OPTIMAL` and `LOCALLY_SOLVED` should be expected in normal conditions.

**Comment by ccoffrin** [comment]
For a complete list have a look at, http://www.juliaopt.org/MathOptInterface.jl/v0.9/apireference/#Termination-Status-1

**Comment by nicoleepp** [comment]
> For a complete list have a look at, http://www.juliaopt.org/MathOptInterface.jl/v0.9/apireference/#Termination-Status-1

I'm not sure if the `LIMIT` status's should make `isconverged` return `true` here as the solution is not converged when the limit is hit. The only two that seem appropriate to me are
`SOLUTION_LIMIT, OBJECTIVE_LIMIT`. 

What is your opinion on which ones we should include?

**Comment by ccoffrin** [comment]
I don't really know the context you are going for, but strictly speaking I would consider everything in the `OK` category to be _converged_.  If your semantics is more like converged and the algorithm completed with a feasible solution, then maybe this subset would be suitable,
OPTIMAL, LOCALLY_SOLVED, ALMOST_OPTIMAL, ALMOST_LOCALLY_SOLVED.

One nice new feature of JuMP v0.19 is that you can make a distinction if the algorithm finished or hit a limit (i.e. `TerminationStatus`) vs the solution feasibility (i.e. `PrimalStatus`).  You might consider providing both types of information to the frontend.

**Comment by eperim** [comment]
I would suggest using

`true`:
OPTIMAL
LOCALLY_SOLVED
ALMOST_OPTIMAL
ALMOST_LOCALLY_SOLVED

`false`:
everything else

but I agree with @ccoffrin that, since the information is available now in JuMP, we could add a new field, such as `termination_status`, with that information as well.

**Comment by ccoffrin** [comment]
@nicoleepp shall we merge this then?

**Comment by nicoleepp** [comment]
> @nicoleepp shall we merge this then?

I will update it to include the `ALMOST_OPTIMAL` and `ALMOST_LOCALLY_SOLVED`.

**Comment by nicoleepp** [comment]
Sorry for the delay @ccoffrin, should be good to go now

**Pull request merged**
