### PR TITLE
Remove Manifest.toml

### LINKED ISSUE #57: Remove Manifest.toml
Just using the Project.toml should be good enough as the Manifest.toml is recreated locally for everyone from the Project.toml

### PR DESCRIPTION
**Pull request by nicoleepp**
Closes #57

### CODE REVIEW

**Comment by nicoleepp** [comment]
@ccoffrin Ipopt.jl was missing from the Project.toml, it should work now

**Comment by ccoffrin** [comment]
Ipopt is used only in the tests, so it would appear in `extras` only and not `deps`, correct?

**Comment by nicoleepp** [comment]
> Ipopt is used only in the tests, so it would appear in `extras` only and not `deps`, correct?

Yeah, you're right. Thinking about it I'm not sure what fixes this situation. At least we know why it was failing

**Comment by ccoffrin** [comment]
Interestingly everything seems to be working on Julia `nightly`, so that leads me to believe the Project.toml is reasonable and we are hitting a corner case of the package manager that will be resolved in the future.

**Pull request closed without merging**
