### PR TITLE
Use PowerSystemsUnits.jl

### PR DESCRIPTION
**Pull request by nicoleepp**
@eperim

### CODE REVIEW

**Comment by ccoffrin** [comment]
Can you tell me a bit about why a separate package is necessary?  I am not a big fan of more packages, if it can be avoided (increases maintenance significantly).

**Comment by nicoleepp** [comment]
We use PowerSystemsUnits.jl internally separate from PowerModelsAnnex.jl, and from the comments in the deleted code it was intended to be its own package all along. Maybe @eperim can comment more though.

**Comment by ccoffrin** [comment]
Ok, as long as you all are willing to do the maintenance on PowerSystemsUnits, this is fine.

You might be careful with the `PowerSystemsUnits` it could get confused with the package `PowerSystems`?  Maybe `PowerSystems` would be willing to integrate and start using `PowerSystemsUnits`?

**Comment by eperim** [comment]
`PowerSystemUnits` is just really a pretty small extension to `Unitful.jl`, because the original one does not have some units we need. It should be something very low maintenance. I have never used `PowerSystems` before, so I can't comment on that.

**Pull request merged**
