### PR TITLE
changing the units for PWLCost.

### PR DESCRIPTION
**Pull request by mjamei19**

### CODE REVIEW

**Comment by mjamei19** [comment]
pending on https://github.com/invenia/PowerSystemsUnits.jl/pull/8

**Comment by ccoffrin** [comment]
@nicoleepp, I think we are waiting on a tag of https://github.com/invenia/PowerSystemsUnits.jl so this will work?

**Comment by nicoleepp** [comment]
Thanks for bringing this to my attention. Has been tagged now https://github.com/JuliaLang/METADATA.jl/pull/20646

**Comment by ccoffrin** [comment]
@mjamei19, thanks for this contribution.  The `REQUIRE` file needs to be updated to reflect the fixed version of PowerSystemUnits.

**Comment by ccoffrin** [comment]
CI tests need to pass before merging.

**Comment by mjamei19** [comment]
@ccoffrin I'll look into the CI tests today.

**Comment by ccoffrin** [comment]
Looks good to me.  Thanks!

**Pull request merged**
